name: CI

on: 
  push:
    branches: 
    - "*"
  pull_request:
    branches: 
    - master

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: SPM build
      run: swift build

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['5.1', '5.2', '5.3']
    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: 's3'
    container:
      image: swift:${{ matrix.tag }}
      env:
        S3_ENDPOINT : "http://localstack:4566"
    steps:
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata zlib1g-dev
    - name: Print endpoints
      run: |
        echo "S3 : ${S3_ENDPOINT}"
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test
      run: swift test -Xswiftc -DDEBUG
